### ISSUE TITLE
Latest commit reverted PR #11

### ISSUE THREAD

**Issue by mareklinka** [autofac/Autofac.Extras.Moq#13]
Hi. It seems the latest commit `7077321fb67b616ddfbd23d843bfb418d619226b` reverted the changes merged in pull request #11. This means the nuget package 4.1,0 is still throwing the exception described in #10.

Should I open a new PR or can you fix this on your end?

**Comment by tillig** [comment]
Grabbed your PR. Sorry about that. Was trying to update the build to see if I could get the Travis CI build working again prior to release and missed this somehow.

**Comment by mareklinka** [comment]
No worries, stuff happens. Thanks for taking care of it.
