### ISSUE TITLE
Not possible to update package to version 4.2.0 for pure .Net 4.5 framework project in VS 2015

### ISSUE THREAD

**Issue by PashoQ** [autofac/Autofac.Extras.Moq#16]
I have encountered error while updating package Autofac.Extras.Moq from version 4.0.0 to version 4.2.0.
I use internal nugget repository on which .Net Standart Assemblies are not allowed.
Could something be done to remove 'System.ComponentModel.TypeConverter' as Nuget Dependency when targeting preinstalled .Net Framework 4.5?

Attempting to gather dependency information for multiple packages with respect to project 'CDOWebService.Tests', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 780,99 ms
Attempting to resolve dependencies for multiple packages.
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Autofac.Extras.Moq 4.0.0'
Unable to resolve dependency 'System.ComponentModel.TypeConverter'. Source(s) used: BICS_NUGET.
========== Finished ==========
Time Elapsed: 00:00:01.7135439

**Comment by tillig** [comment]
It's actually Moq that requires System.ComponentModel.TypeConverter. We have a reference here to avoid a different issue where Moq actually wants a version of that assembly that was delisted.

You will likely have to update your internal NuGet server. .NET Standard assemblies are compatible with full .NET Framework projects and you're going to see a lot more things that only target .NET Standard to ensure portability.

**Comment by PashoQ** [comment]
I understand that you need reference to System.ComponentModel.TypeConverter assembly.
What is strange for me that you force to use NuGet package, while assembly itself is part of installed 4.5 .Net framework.
Update of internal NuGet Server is no an option for me, unfortunately
