### ISSUE TITLE
RegisterDecorator not functioning as expected

### ISSUE THREAD

**Issue by Thorarin** [autofac/Autofac.Extras.Moq#21]
When using AutoMock, it's possible to build the underlying container that is used to resolve dependencies. This is useful if a test requires a few specific dependencies are fulfilled by the actual implementations, for example.

I've run into a problem when using this pattern: registered decorators seem to be ignored.
Instead of my registered decorator getting injected, a new new mock is automatically created and used instead.

In code, this does not work as expected:

```
var autoMock = AutoMock.GetLoose(builder =>
{
    builder.RegisterType<Service>().Named<IService>("uncached");
    builder.RegisterDecorator<IService>(
        (ctx, inner) => new CachingService(inner), "uncached");
});
```

By comparison, this workaround does the job:

```
var autoMock = AutoMock.GetLoose(builder =>
{
    builder.RegisterType<Service>().Named<IService>("uncached");
    builder.RegisterType<CachingService>()
        .WithParameter(new ResolvedParameter(
            (pi, ctx) => pi.ParameterType == typeof(IService),
            (pi, ctx) => ctx.ResolveNamed<IService>("uncached")))
        .As<IService>();
});
```

I may take a look myself as to the cause of this, but I can't make any promises :smile:

**Used versions**
```
<package id="Autofac" version="4.8.1" targetFramework="net471" />
<package id="Autofac.Extras.Moq" version="4.3.0" targetFramework="net471" />
<package id="Moq" version="4.10.0" targetFramework="net471" />
```

**Reproduction**
I've added a test that demonstrates the problem in this fork:
https://github.com/Thorarin/Autofac.Extras.Moq/tree/feat/decorators

**Comment by alistairjevans** [comment]
As of the imminent version 5.0 release of this integration, this issue has been resolved.
