### ISSUE TITLE
Support for Autofac Property Injection

### ISSUE THREAD

**Issue by mlxyz** [autofac/Autofac.Extras.Moq#27]
My [similar question](https://stackoverflow.com/q/58963632/10289094) on Stackoverflow.
***

Hi,

consider the following class, which acts as a base class for all of my view models:
```c#
public class ViewModelBase
{
    public IService Service { get; protected set; }
}
```
After reading [this](https://stackoverflow.com/a/7200082/10289094) answer on StackOverflow, I've decided to use property injection (with `Autofac.Core.NonPublicProperty`) to wire the `IService` dependency into all derived view models:
```c#
containerBuilder.RegisterType(typeof(ViewModelBase)).AutoWireNonPublicProperties();
```
This is my test method for the `ViewModelBase` class:
```c#
using var mock = AutoMock.GetLoose();
var viewModelBase = mock.Create<ViewModelBase>();
Assert.NotNull(viewModelBase.Service);
```
Obviously this fails, because `Autofac.Extras.Moq` only supports constructor injection of mocks.

Will property injection be supported in the future, or is there any other elegant way of injecting dependencies into the `ViewModelBase` class during testing?

**Comment by alistairjevans** [comment]
Sorry for the delay on this one.

Is it sufficient to configure a service as follows:

```csharp
using (var mock = AutoMock.GetLoose(
    c => c.RegisterType<ComponentWithPropertyInjection>().PropertiesAutowired()))
{
    var result = mock.Create<ComponentWithPropertyInjection>();
    Assert.NotNull(result.Service);
}
```
Property injection works for me if I configure it in the configuration callback.

Any other options for specifying the property injection at creation time doesn't give any particularly great options.

**Comment by tillig** [comment]
Since property injection isn't the most common scenario I think configuring it this way makes sense. Ideally folks would use constructor injection wherever possible. I'm going to call this one solved since there's a way to make it happen.
