### ISSUE TITLE
method not found exception with autofac 5.0.0 

### ISSUE THREAD

**Issue by codingL3gend** [autofac/Autofac.Extras.Moq#28]
upgrading to autofac 5.0.0 breaks the latest version of this library with method not found exception for method Autofac.RegistrationExtensions.RegisterSource. will support for this be provided?

**Comment by tillig** [comment]
[From the release notes](https://github.com/autofac/Autofac/releases/tag/v5.0.0)

> ## Still TODO
>
> Now that Autofac 5.0 is out, there is still a lot to do. We'll be working on these things as fast as we can:
>
> - Updating integration packages we support so they ensure compatibility with Autofac 5.
> - Updating the documentation to reflect the above changes.
>
> Some of this is sitting in branches ready to go, other things need to be done now that we have this core package out there.
>
> **If your favorite integration isn't ready yet, we're doing our best.** Rather than filing "When will this be ready?" issues, consider pull requests with the required updates.
