### ISSUE TITLE
MockBehaviour.Strict and IDisposable fails when AutoMock disposes.

### ISSUE THREAD

**Issue by JarkoDubbeldam** [autofac/Autofac.Extras.Moq#35]
I am having a similar issue as #19 with Moq 4.13.1, Autofac.Extras.Moq 5.0.0, NUnit 3.12.0: Mocking `IDisposable` or interfaces inheriting from it with mockbehaviour strict results in an exception when `AutoMock` is disposed. From the perspective of the test, it shouldn't fail the test after the mocked container is being disposed. 

Example:

```
    [Test]
    public void DisposableMockTest() {
      using var mock = AutoMock.GetStrict();
      var instance = mock.Create<ClassWithDisposableDependancy>();

      var result = instance.DoStuff();
      Assert.That(result, Is.EqualTo(5));
    }

    public class ClassWithDisposableDependancy {
      private readonly IDisposable disposable;

      public ClassWithDisposableDependancy(IDisposable disposable) {
        this.disposable = disposable;
      }

      public int DoStuff() {
        return 5;
      }
    }
```
It fails with the following exception:

```
Message: 
    System.AggregateException : One or more errors occurred. (Rethrown)
      ----> NUnit.Framework.Internal.NUnitException : Rethrown
      ----> Moq.MockException : IDisposable.Dispose() invocation failed with mock behavior Strict.
    All invocations on the mock must have a corresponding setup.
  Stack Trace: 
    Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    Task.Wait(Int32 millisecondsTimeout)
    TimeoutCommand.Execute(TestExecutionContext context)
    --NUnitException
    Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
    MethodWrapper.Invoke(Object fixture, Object[] args)
    TestMethodCommand.InvokeTestMethod(TestExecutionContext context)
    TestMethodCommand.RunTestMethod(TestExecutionContext context)
    TestMethodCommand.Execute(TestExecutionContext context)
    <>c__DisplayClass2_0.<Execute>b__0()
    Task`1.InnerInvoke()
    <.cctor>b__274_0(Object obj)
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --MockException
    FailForStrictMock.Handle(Invocation invocation, Mock mock)
    IInterceptor.Intercept(Invocation invocation)
    Interceptor.Intercept(IInvocation invocation)
    AbstractInvocation.Proceed()
    IDisposableProxy.Dispose()
    Disposer.Dispose(Boolean disposing)
    Disposable.Dispose()
    LifetimeScope.Dispose(Boolean disposing)
    Disposable.Dispose()
    Container.Dispose(Boolean disposing)
    Disposable.Dispose()
    AutoMock.Dispose(Boolean disposing)
    AutoMock.Dispose()
    Example.DisposableMockTest() line 177
```

It seems that when the Automock container is disposed, it's disposing all of its registered types. The mocked types being strict, this fails and throws. I'm not sure if it is possible to make a special case for mocked items, since it looks like it might be in the common Autofac code, which might be problematic.

**Comment by alsami** [comment]
I don't think that's a problem of the given extension looking at a part of the exception:

```
invocation failed with mock behavior Strict.
    All invocations on the mock must have a corresponding setup.
```

Which is happening during that call `IDisposable.Dispose()`. `Moq` throws an exceptions on invocations that [do not have a setup action](https://github.com/Moq/moq4/wiki/Quickstart#customizing-mock-behavior).

Have you tried `AutoMock.GetLoose()` instead? if I am not mistaken, then the error should not be thrown. 

@alistairjevans any thoughts on that?

**Comment by alistairjevans** [comment]
If you have a service that requires disposal (and you want Strict rules), then you will need to set it up.  If you call `AutoMock.Mock<IDisposable>()`, you can get the mock for `IDisposable` and set up the `Dispose` method yourself.

I'd be reluctant to special-case a particular service by auto-setting-up the dispose method internally; it could lead to confusion.

**Comment by JarkoDubbeldam** [comment]
I understand the reluctance. The reason I suggested it was that if the SUT does not dispose of the `IDisposable` mock itself, but Autofac. With Autofac in general the created services are owned and disposed by Autofac's lifetime scopes. From what I understand, it's not the consuming service's task to dispose of any dependencies. That makes it weird that a test for that service would have to setup its dependencies to be able to be disposed. Especially since in the general case, that SUT shouldn't be disposing of its dependencies in the first place.

I'm also struggling thinking of test-cases where you'd want a test to fail because the dispose method wasn't setup at the point the container is being disposed.

------
I do realise that the workaround is relatively small compared to the changes required. But I did want to respectfully point out this gotcha.

**Comment by alistairjevans** [comment]
You make some valid points, and I do understand that having auto-mocked disposable services that don't implement `Dispose` can be a little strange. On the other hand, by specifying that you want `Strict` mocking rules, you're explicitly saying _"I want to say exactly what is implemented and what isn't"_, so being partially `Loose` in that mode feels wrong.

Additionally, if we were to add a 'default' mock for `Dispose`, I also don't know how that would work if someone specified their own `Setup` of `Dispose`? Which would take precedence?

My feeling is that is a potentially confusing case (and a gotcha), but one that could be best served by an addition to the Autofac Documentation for the Moq integration, with a note/sub-section about "Disposables in Strict Mode" and an example workaround.

**Comment by JarkoDubbeldam** [comment]
> On the other hand, by specifying that you want Strict mocking rules, you're explicitly saying "I want to say exactly what is implemented and what isn't"

It also means that I want to test exactly what my tested service is calling, not what `AutoMock` is doing afterwards ;)

Setting up the mock only when the container is disposed might be a way to interfere as little as possible with the user's setup. Or swallowing the `MockException`. But I'm not 100% sure on what work is exactly being done when disposing `AutoMock` that might interfere with any setups.

**Comment by alistairjevans** [comment]
Moq doesn't supply a straight-forward way of asking "has this method already been set up?". So I don't think we can even detect that a user has supplied a `Setup` for `Dispose`, so we wouldn't know whether to apply our own.

We _could_ mark all generated mocks as `ExternallyOwned`, so the container never disposes of them...

Actually, that might be a potential solution to this.  You could argue that Mocks are 'owned' by Moq, rather than the container anyway, and won't hold any actual resources.  But if you call Dispose on the mock from inside your own component, your behaviour would still take effect (or throw if you haven't set it up in Strict mode).

Playing devil's advocate, I'm trying to imagine a use-case where a developer has defined a Dispose call for a mock, where the mock is only disposed by the container, but I can't think of one right now...

**Comment by JarkoDubbeldam** [comment]
> Playing devil's advocate, I'm trying to imagine a use-case where a developer has defined a Dispose call for a mock, where the mock is only disposed by the container, but I can't think of one right now...

I can only think of a scenario where they are testing the container itself, but then they probably shouldn't be using `AutoMock` but `Autofac` itself.

**Comment by alistairjevans** [comment]
I can't imagine what meaningful disposing a mock would need to do; it is a mock after all.

Would you be willing to put together a PR with the change to make all Mock registrations externally owned, with some associated unit tests? Then we can give this a further review.

**Comment by JarkoDubbeldam** [comment]
I'll take a look at it this afternoon.

**Comment by tillig** [comment]
Is there a use case where folks using strict mocks might want to ensure disposables are disposed?  That's sort of the opposite situation to this - where someone wants to ensure resources are cleaned up as expected when the container is disposed.

I get that setting up `Dispose` seems like a pain, but if folks _weren't_ using `AutoMock` and were setting up mocks manually, putting a disposable mock through a `using` statement or something would still end up calling `Dispose` on it implicitly and would fail the test.

I just want to make sure that if we un-strict the strict mocks that we won't be inadvertently breaking someone else's tests that assume they need to set up `Dispose` and then suddenly... it's no longer being called and all their tests fail. There may be valid reasons where folks _want_ to set up `Dispose` as a required thing.

**Comment by JarkoDubbeldam** [comment]
Currently, the following test exists in the repo:

```
        [Fact]
        public void DisposableStrictMocking()
        {
            using (var mock = AutoMock.GetStrict())
            {
                // Should not throw on dispose of AutoMock.
                mock.Mock<IInheritFromDisposable>().Setup(x => x.Dispose());
                var sut = mock.Create<ConsumesDisposable>();
            }
        }
```

If I modify it to validate that `Dispose` is called, the test fails:

```
        [Fact]
        public void DisposableStrictMocking()
        {
            using (var mock = AutoMock.GetStrict())
            {
                // Should not throw on dispose of AutoMock.
                mock.Mock<IInheritFromDisposable>().Setup(x => x.Dispose()).Verifiable();
                var sut = mock.Create<ConsumesDisposable>();
            }
        }

    Moq.MockException : The following setups were not matched:
    IInheritFromDisposable x => x.Dispose()
```
This means that even without the suggested changes, the call to `Dispose` by `AutoMock` can't be part of people's tests right now, since it doesn't appear to work. It seems that the verification is done before disposal (which makes sense).

**Comment by tillig** [comment]
Fair enough! Thanks for checking. It's good to know the change wouldn't break folks.

**Comment by JarkoDubbeldam** [comment]
> I get that setting up Dispose seems like a pain, but if folks weren't using AutoMock and were setting up mocks manually, putting a disposable mock through a using statement or something would still end up calling Dispose on it implicitly and would fail the test.

I totally agree with this part. The goal of the proposed solution is to leave any setups that a user might make, and any calls to `Dispose` they might make (also through `using` blocks) in place and just change whether the mocks are disposed along with `AutoMock` or not. So the big question is whether there is any conceivable reason we might want to ensure a mock gets disposed?

**Comment by JarkoDubbeldam** [comment]
(from the PR:)
> >  Would it make sense to make the same changes to RegisterMock? I noticed there were few tests covering that, so I left it alone for now.

> Maybe, yes; we're not creating the mock ourselves here, but it is being registered in a similar way, so should be considered ExternallyOwned as well.

@tillig Do you have an opinion about this?

**Comment by tillig** [comment]
I have no strong opinion; it would make sense to behave in a consistent fashion, so I'm okay with making that additional change.
