### ISSUE TITLE
Is this repository still actively maintained?

### ISSUE THREAD

**Issue by Leandore** [autofac/Autofac.Extras.Moq#45]
Hi all,

I was curious, this repository still being maintained? The reasons for my questions are

1. There has not been many commits during the last year
2. There dependancy on Moq is a slightly older version (https://github.com/moq/moq4) , 4.7 where Moq is up to 4.18

Thank you,

**Comment by tillig** [comment]
Depends on what you mean by "actively." The code still works and there hasn't been any major issue reported, so there hasn't been a need for commit. You can update your own local reference of any transitive dependency like Moq in your own project and things should still work - [we don't upgrade unless there's a technical reason to do so](https://docs.autofac.org/en/latest/faq/binding-redirect.html). There are only really two (sometimes three) Autofac maintainers - there isn't a big team and no one is paid for any work here, so any time allocated to core Autofac and the 20+ integration packages basically boils down to two people giving up hobbies, family, holidays, and other free time to provide free software and support (don't forget answering all the questions here and in forums and StackOverflow and Twitter and...).

What that means is that things may be _active_ but not a _priority_. If there's nothing broken, there's nothing to fix. Things also get prioritized a bit based on what folks _want_ to work on - if you're giving up your personal time, it's better if it's something interesting and/or something you'll use. I, for example, don't use Moq integration with Autofac, nor do I use ServiceFabric, so those integration libraries, for me, end up getting a lower priority than something in core Autofac.

If there's something you desire in this particular library, we welcome community pull requests. If you would like to personally volunteer to take ownership of this integration package (and provide ongoing patches and review the PRs and address the issues and answer all the questions in all the places, etc.) we'd be more than happy to talk about that, too. [We've put out several calls for owners over the years](https://www.paraesthesia.com/archive/2019/07/05/autofac-still-looking-for-owners/) and get very little in the way of response.
