### ISSUE TITLE
netstandard support

### ISSUE THREAD

**Issue by jasonwilliams200OK** [autofac/Autofac.Extras.Moq#5]
This project has two dependencies: http://www.nuget.org/packages/Autofac.Extras.Moq/, both support netstandard. At least support a portable profile so we can use with netcoreapp on Unix with no Mono installed.

If you want I can prepare a pull request to expedite this issue. :)

Thanks.

/cc @DanielSchaffer (interested party)

**Comment by tillig** [comment]
Oh, yup, looks like they just released that for Moq yesterday.

A PR would be awesome. It may otherwise take a while for us to get to this given the many integration libraries we're still converting. Thanks!

**Comment by jasonwilliams200OK** [comment]
> looks like they just released that for Moq yesterday

not since the garden of Eden, but i am using Moq with xunit on netcore for over a month now.. (June 6 was the release date of that glorious alpha build) :)

> A PR would be awesome.

cool will do that. Incidentally, do we need to keep net30 (.NET Framework v3.0) support?

**Comment by tillig** [comment]
Good question. Autofac itself no longer supports net30, so skip it. Just go with the lowest common denominator between Autofac and Moq and we should be okay.
